USE [E:\FDA\TEST TECNICOS - PARA INGRESOS LABORALES\PRACTICOS\MVCAPPRESEARCH\MVCAPPRESEARCH\APP_DATA\DATABASE.MDF]
GO


/****** Object:  Table [dbo].[Events]    Script Date: 20/10/2016 9:24:06 p. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[Events](
	[EventId] [int] NOT NULL IDENTITY(1,1),
	[EventTitle] [varchar](50) NOT NULL,
	[Technology] [varchar](50) NOT NULL,
	[StartingDate] [datetime] NOT NULL,
	[RegistrationLink] [varchar](1000) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[EventId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


